services:
    web:
        container_name: apache-laravel
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            -   ./:/usr/src/ku1-newsletter-admin
        working_dir: /usr/src/ku1-newsletter-admin/public
        ports:
            -   80:80
    db:
        container_name: db
        image: mysql
        volumes:
            - ./database/data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: ku1-newsletter
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        ports:
            - 9906:3306
